services:
  - type: web
    name: plant-therapy-backend
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
